const applications = [
  {
    id: 1,
    name: 'Jane Cruz',
    age: 22,
    gender: 'Female',
    email: 'jane@example.com',
    contact: '09123456789',
    address: 'Tanauan City, Batangas',
    occupation: 'Student',
    citizenship: 'Filipino',
    program: 'CLIQUE',
    date: '2025-05-18',
    status: 'Pending',
    reason: 'I want to help the community.',
    validIdFilename: "jane-valid-id.jpg",
  },
  {
    id: 2,
    name: 'Marco Reyes',
    age: 25,
    gender: 'Male',
    email: 'marco@example.com',
    contact: '09987654321',
    address: 'Lipa City, Batangas',
    occupation: 'Nurse',
    citizenship: 'Filipino',
    program: 'CARE',
    date: '2025-05-17',
    status: 'Pending',
    reason: 'This fits my advocacy.',
  },
];

export default applications;